name: Python Package using Conda
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.7, 3.8]
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge
      - run: conda --version
      - run: which python
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda env update --file environment-cpu.yml --name base
      - name: install convml_tt
        run: |
          pip install .
# 2021/2/24: skip linting for now
#      - name: Lint with flake8
#        run: |
#          conda install flake8
#          # stop the build if there are Python syntax errors or undefined names
#          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: install luigi (for data generation pipeline tests)
        run: |
          pip install luigi isodate
      - name: install satpy, cartopy, xesmf (for data generation pipeline tasks)
        run: |
          conda install -c conda-forge satpy cartopy xesmf
      - name: install satdata (for data generation pipeline tests)
        run: |
          pip install git+https://github.com/leifdenby/satdata#egg=satdata
      - name: Test with pytest
        run: |
          conda install pytest
          pytest
